[package]
name = "starknet-handler"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
# server = { path = "../server" }

eyre = { workspace = true }
dotenv = { workspace = true }
tokio = { workspace = true }

starknet-crypto = "0.7.2"
starknet = "0.12"
